# Generated by Django 2.2.10 on 2020-11-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombreArtistico', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'artista_artista',
            },
        ),
    ]
