# Generated by Django 2.2.10 on 2020-11-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='caratula',
            new_name='archivo',
        ),
    ]
