# Generated by Django 2.2.10 on 2020-11-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancion', '0002_auto_20201123_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='album_id',
            new_name='album',
        ),
    ]
